const DEST = [
  {name: 'Red River Gorge',
  location: 'USA (KY)',
  rock: 'Sandstone',
  options: ['Mexico - Limestone', 'USA (WV) - Sandstone', 'Jordan - Granite', 'USA (KY) - Sandstone'],
  answer: '4',
  style: 'sport/trad',
  picture: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVl5rBRL-5W4otkh1BFtypNu08yLsGIB7C6yTZFkhzPOwb-fzTVQ'
},
{name: 'Verdon Gorge',
location: 'France',
rock: 'Limestone',
options: ['Italy - Limestone', 'France - Limestone', 'Laos - Basalt', 'USA (OR) - Volcanic Tuff'],
answer: '2',
style: 'sport',
picture: 'https://www.planetmountain.com/img/1/4085.jpg'
},
{name: 'Rocky Mountain National Park',
location: 'USA (CO)',
rock: 'Granite',
options: ['USA (CO) - Granite', 'USA (WV) - Sandstone', 'Canada - Granite', 'USA (WY) - Sandstone'],
answer: '1',
style: 'trad/bouldering',
picture: 'https://images.unsplash.com/photo-1535653723633-c5e8fa52df70?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80'
},
{name: 'Margalef',
location: 'Spain',
rock: 'Conglomerate',
options: ['Brazil - Granite', 'Greece - Conglomerate', 'Spain - Conglomerate', 'USA (KY) - Sandstone'],
answer: '3',
style: 'sport',
picture: 'https://d37d73vc0i3fom.cloudfront.net/photos/000/128/128736/size_xl-26280eca2bdc.jpg'
},
{name: 'Yangshuo',
location: 'China',
rock: 'Limestone',
options: ['Thailand - Limestone', 'USA (CO) - Sandstone', 'Israel - Sandstone', 'China - Limestone'],
answer: '4',
style: 'sport',
picture: 'https://www.easytourchina.com/images/Photo/yangshuo-rock-climbing-festival-2014/p596_d20141020144115.jpg'
},
{name: 'Rifle',
location: 'USA (CO)',
rock: 'Limestone',
options: ['Mexico - Limestone', 'USA (CO) - Limestone', 'Spain - Granite', 'USA (NV) - Granite'],
answer: '2',
style: 'sport',
picture: 'https://d1vs4ggwgd7mlq.cloudfront.net/wp-content/uploads/2017/09/RI-Rifle-CMB-2-e1506983733339.jpg'
},
{name: 'Tonsai',
location: 'Thailand',
rock: 'Limestone',
options: ['Thailand - Limestone', 'USA (WV) - Sandstone', 'China - Limestone', 'Laos - Limestone'],
answer: '1',
style: 'sport',
picture: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
},
{name: 'Rocklands',
location: 'South Africa',
rock: 'Sandstone',
options: ['Spain - Limestone', 'USA (WV) - Sandstone', 'South Africa - Sandstone', 'Canada - Limestone'],
answer: '3',
style: 'bouldering',
picture: 'http://www.climbandmore.com/upload/melissa_rocklands.jpg'
},
{name: 'Fontainebleau',
location: 'France',
rock: 'Sandstone',
options: ['Mexico - Limestone', 'France - Sandstone', 'Belgium - Granite', 'USA (KY) - Volcanic Tuff'],
answer: '2',
style: 'bouldering',
picture: 'https://thesevereclimber.files.wordpress.com/2017/04/20170415_121615.jpg?w=830&h=374&crop=1'
},
{name: 'Yosemite National Park',
location: 'USA (CA)',
rock: 'Granite',
options: ['USA (CA) - Granite', 'USA (WV) - Sandstone', 'Jordan - Granite', 'USA (KY) - Sandstone'],
answer: '1',
style: 'trad/bouldering',
picture: 'https://images.unsplash.com/photo-1520220356818-297be96cb509?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60'
}
]